import "./globals.css";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import Sidebar from "./components/Sidebar";
import { Providers } from "./providers";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex min-h-svh bg-zinc-950",
          urbanist.className,
        )}
      >
        <Providers>
          <Sidebar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
